version: "3"

services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: videostreaming
      MYSQL_USER: videostreaming
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - ./db-data/mysql/:/var/lib/mysql

  cache:
    image: redis:7.4-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./db-data/redis/:/data

  kafka:
    image: bitnami/kafka:3.4
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_NODE_ID: 1

  api-gateway:
    image: alpine:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./bin/api-gateway:/app/api-gateway
      - ./api-gateway/configs/:/app/configs/
    entrypoint: [ "/app/api-gateway" ]

  user-service:
    image: alpine:latest
    container_name: user-service
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - ./bin/user-service:/app/user-service
      - ./user-service/configs/.env:/.env
      - ./user-service/migrations:/app/migrations/
    entrypoint: [ "/app/user-service" ]
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=jobs sslmode=disable timezone=Europe/Amsterdam connect_timeout=5"

  video-service:
    build:
      context: ./video-service
      dockerfile: Dockerfile
    container_name: video-service
    restart: unless-stopped
    ports:
      - "5002:5002"
    volumes:
      - ./bin/video-service:/app/video-service
      - ./video-service/configs/.env:/.env
      - ./output/:/output
      - ./logs/:/logs
    entrypoint: [ "/app/video-service" ]
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=jobs sslmode=disable timezone=Europe/Amsterdam connect_timeout=5"

  streaming-service:
    image: alpine:latest
    container_name: streaming-service
    ports:
      - "5003:5003"
    volumes:
      - ./bin/streaming-service:/app/streaming-service
    entrypoint: [ "/app/streaming-service" ]

volumes:
  postgres_data:
    driver: local

networks:
  shared:
    driver: bridge