name: Run Tests
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Download Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          check-latest: true
        id: go

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          go get -v -t ./...

      - name: Test
        run: |
          go test ./... -v